// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order.Persistence.Database;

namespace Order.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230503195129_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Order")
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Order.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 630, DateTimeKind.Local).AddTicks(3981),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1247),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 3,
                            ClientId = 3,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1268),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 4,
                            ClientId = 4,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1270),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 5,
                            ClientId = 5,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1272),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 6,
                            ClientId = 6,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1275),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 7,
                            ClientId = 7,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1277),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 8,
                            ClientId = 8,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1278),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 9,
                            ClientId = 9,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1279),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 10,
                            ClientId = 10,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1281),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 11,
                            ClientId = 11,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1282),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 12,
                            ClientId = 12,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1284),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 13,
                            ClientId = 13,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1285),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 14,
                            ClientId = 14,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1286),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 15,
                            ClientId = 15,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1287),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 16,
                            ClientId = 16,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1288),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 17,
                            ClientId = 17,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1289),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 18,
                            ClientId = 18,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1291),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 19,
                            ClientId = 19,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1293),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        },
                        new
                        {
                            OrderId = 20,
                            ClientId = 20,
                            CreatedAt = new DateTime(2023, 5, 3, 16, 51, 29, 631, DateTimeKind.Local).AddTicks(1294),
                            PaymentType = 1,
                            Status = 1,
                            Total = 100m
                        });
                });

            modelBuilder.Entity("Order.Domain.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            Total = 1m,
                            UnitPrice = 1m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            ProductId = 2,
                            Quantity = 2,
                            Total = 2m,
                            UnitPrice = 2m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            ProductId = 3,
                            Quantity = 3,
                            Total = 3m,
                            UnitPrice = 3m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            ProductId = 4,
                            Quantity = 4,
                            Total = 4m,
                            UnitPrice = 4m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            ProductId = 5,
                            Quantity = 5,
                            Total = 5m,
                            UnitPrice = 5m
                        },
                        new
                        {
                            OrderDetailId = 6,
                            ProductId = 6,
                            Quantity = 6,
                            Total = 6m,
                            UnitPrice = 6m
                        },
                        new
                        {
                            OrderDetailId = 7,
                            ProductId = 7,
                            Quantity = 7,
                            Total = 7m,
                            UnitPrice = 7m
                        },
                        new
                        {
                            OrderDetailId = 8,
                            ProductId = 8,
                            Quantity = 8,
                            Total = 8m,
                            UnitPrice = 8m
                        },
                        new
                        {
                            OrderDetailId = 9,
                            ProductId = 9,
                            Quantity = 9,
                            Total = 9m,
                            UnitPrice = 9m
                        },
                        new
                        {
                            OrderDetailId = 10,
                            ProductId = 10,
                            Quantity = 10,
                            Total = 10m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            OrderDetailId = 11,
                            ProductId = 11,
                            Quantity = 11,
                            Total = 11m,
                            UnitPrice = 11m
                        },
                        new
                        {
                            OrderDetailId = 12,
                            ProductId = 12,
                            Quantity = 12,
                            Total = 12m,
                            UnitPrice = 12m
                        },
                        new
                        {
                            OrderDetailId = 13,
                            ProductId = 13,
                            Quantity = 13,
                            Total = 13m,
                            UnitPrice = 13m
                        },
                        new
                        {
                            OrderDetailId = 14,
                            ProductId = 14,
                            Quantity = 14,
                            Total = 14m,
                            UnitPrice = 14m
                        },
                        new
                        {
                            OrderDetailId = 15,
                            ProductId = 15,
                            Quantity = 15,
                            Total = 15m,
                            UnitPrice = 15m
                        },
                        new
                        {
                            OrderDetailId = 16,
                            ProductId = 16,
                            Quantity = 16,
                            Total = 16m,
                            UnitPrice = 16m
                        },
                        new
                        {
                            OrderDetailId = 17,
                            ProductId = 17,
                            Quantity = 17,
                            Total = 17m,
                            UnitPrice = 17m
                        },
                        new
                        {
                            OrderDetailId = 18,
                            ProductId = 18,
                            Quantity = 18,
                            Total = 18m,
                            UnitPrice = 18m
                        },
                        new
                        {
                            OrderDetailId = 19,
                            ProductId = 19,
                            Quantity = 19,
                            Total = 19m,
                            UnitPrice = 19m
                        },
                        new
                        {
                            OrderDetailId = 20,
                            ProductId = 20,
                            Quantity = 20,
                            Total = 20m,
                            UnitPrice = 20m
                        });
                });

            modelBuilder.Entity("Order.Domain.OrderDetail", b =>
                {
                    b.HasOne("Order.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
